language: python

python:
  - "3.6"      
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - python3-pyqt5

install:
  - pip3 install pylint

git:
  lfs_skip_smudge: true

branches:
  only:
    - master

script: 
  - pylint src/Welcome_Window1/Main_File.py
