from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(950, 517)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("Line {\n"
"    background-color: #666666;\n"
"    }\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.Avatar = QtGui.QLabel(self.centralwidget)
        self.Avatar.setGeometry(QtCore.QRect(10, 60, 118, 120))
        self.Avatar.setText("")
        self.Avatar.setPixmap(QtGui.QPixmap("icons/Empty_avatar.png"))
        self.Avatar.setScaledContents(True)
        self.Avatar.setObjectName("Avatar")
        self.Avatar.setFixedSize(100,100)
        self.background = QtGui.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 950, 517))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("icons/icon_background.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.left_button = QtGui.QToolButton(self.centralwidget)
        self.left_button.setGeometry(QtCore.QRect(10,8,31,26))
        self.left_button.setIcon(QtGui.QIcon("../icon/icon_list.png"))
        self.left_button.setIconSize(QtCore.QSize(31, 31))
        self.left_button.setGeometry(QtCore.QRect(10, 8, 31, 26))
        self.left_button.setStyleSheet("QToolButton {\n"
"    border: none;\n"
"    \n"
"}")
        self.left_button.setText("")
        self.left_button.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.left_button.setObjectName("left_button")
        self.Settings_but = QtGui.QToolButton(self.centralwidget)
        self.Settings_but.setGeometry(QtCore.QRect(900, 8, 28, 28))
        self.Settings_but.setIcon(QtGui.QIcon("icons/icon_gear_dark.png"))
        self.Settings_but.setIconSize(QtCore.QSize(70,70))
        self.Settings_but.setStyleSheet("border:none;\n")
        self.Settings_but.setText("")
        self.Settings_but.setObjectName("Settings_but")
        self.notification_but = QtGui.QToolButton(self.centralwidget)
        self.notification_but.setGeometry(QtCore.QRect(850, 8, 28, 28))
        self.notification_but.setObjectName("notification_but")
        self.notification_but.setIcon(QtGui.QIcon("icons/icon_notification_dark.png"))
        self.notification_but.setIconSize(QtCore.QSize(28,28))
        self.notification_but.setStyleSheet ("border: none; \n")
        self.day = QtGui.QLabel(self.centralwidget)
        self.day.setGeometry(QtCore.QRect(400, 80, 71, 31))
        self.day.setStyleSheet("color: #FFFFFF;\n"
"font-size: 24px;\n"
"font-weight: 900;\n"
"font-family: Calibri, Candara, Segoe, \"Segoe UI\", Optima, Arial, sans-serif;\n"
"font-style:normal;")
        self.day.setObjectName("day")
        self.Data = QtGui.QLabel(self.centralwidget)
        self.Data.setGeometry(QtCore.QRect(410, 50, 46, 13))
        self.Data.setObjectName("Data")
        self.FirstName = QtGui.QLabel(self.centralwidget)
        self.FirstName.setGeometry(QtCore.QRect(130, 70, 241, 21))
        self.FirstName.setStyleSheet("color: #FFFFFF;\n"
"font-size: 20px;\n"
"font-family: Calibri, Candara, Segoe, \"Segoe UI\", Optima, Arial, sans-serif;\n"
"font-style:normal;")
        self.FirstName.setObjectName("FirstName")
        self.SecondName = QtGui.QLabel(self.centralwidget)
        self.SecondName.setGeometry(QtCore.QRect(130, 100, 241, 21))
        self.SecondName.setStyleSheet("color: #FFFFFF;\n"
"font-size: 20px;\n"
"font-family: Calibri, Candara, Segoe, \"Segoe UI\", Optima, Arial, sans-serif;\n"
"font-style:normal;")
        self.SecondName.setObjectName("SecondName")
        self.dial = QtGui.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(110, 410, 141, 64))
        self.dial.setObjectName("dial")
        self.dial_2 = QtGui.QDial(self.centralwidget)
        self.dial_2.setGeometry(QtCore.QRect(10, 270, 50, 64))
        self.dial_2.setObjectName("dial_2")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 270, 529, 21))
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(390, 130, 551, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.check_box = QtGui.QToolButton(self.gridLayoutWidget)
        self.check_box.setObjectName("check_box")
        self.check_box.setIcon(QtGui.QIcon("icons/Empty_Box_Light.png"))
        self.check_box.setIconSize(QtCore.QSize(24,24))
        self.check_box.setStyleSheet("border:none\n")
        self.gridLayout_2.addWidget(self.check_box, 0, 0, 1, 1)
        self.deal_text = QtGui.QLabel(self.gridLayoutWidget)
        self.deal_text.setObjectName("label_3")
        self.deal_text.setStyleSheet("QLabel{\n"
        "color:FFFFFF;\n"
        "font-weight:bold;\n"
        "font-family: Calibri, Candara, Segoe, \"Segoe UI\", Optima, Arial, sans-serif;\n"
        "}")
        self.gridLayout_2.addWidget(self.deal_text, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.notification_single_but = QtGui.QToolButton(self.gridLayoutWidget)
        self.notification_single_but.setObjectName("notification_single_but")
        self.notification_single_but.setIcon(QtGui.QIcon("icons/icon_timer_dark.png"))
        self.notification_single_but.setStyleSheet("border:none;\n")
        self.notification_single_but.setIconSize(QtCore.QSize(50,34))
        self.gridLayout_2.addWidget(self.notification_single_but, 0, 3, 1, 1)
        self.plus_button = QtGui.QToolButton(self.gridLayoutWidget)
        self.plus_button.setObjectName("plus_button")
        self.plus_button.setIcon(QtGui.QIcon("icons/icon_plus.png"))
        self.plus_button.setIconSize(QtCore.QSize(24,24))
        self.plus_button.setStyleSheet("border:none;\n")
        self.gridLayout_2.addWidget(self.plus_button, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.line = QtGui.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.notification_but.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.day.setText(QtGui.QApplication.translate("MainWindow", "Today", None, QtGui.QApplication.UnicodeUTF8))
        self.Data.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.FirstName.setText(QtGui.QApplication.translate("MainWindow", "FirstName", None, QtGui.QApplication.UnicodeUTF8))
        self.SecondName.setText(QtGui.QApplication.translate("MainWindow", "SecondName", None, QtGui.QApplication.UnicodeUTF8))
        self.Avatar.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.deal_text.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.notification_single_but.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.plus_button.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
